### ISSUE TITLE
[FEATURE] Show Library as Folder structure

### ISSUE THREAD

**Issue by killo3967** [stumpapp/stump#137] opened 2023-05-31 09:32 UTC
All other content server ( Kavita, Komga,etc )displays libraries with the metadata structure. I know a lot of people that has his comics or books in a windows/linux folder structure and want to display it. Ubooquity display the comics with a Folder structure but it wass very old and abandoned proyect.

Could be posible to put an option per library to display as Metada structure, Folder structure o Personal List. 

Marvel o DC has a very high dificult to order. In any case has a 8 depth relations of folders.

Universe -> Sagas -> Series -> Volume (Year/Month) -> Comics

Like this

MARVEL UNIVERSE\EVENT, SAGAS & CROSSOVERS\Marvel Sagas\2005-01 - House of M\Marvel Saga 21 - House of M (2005)

And this is one of the 162 folder of Marvel Sagas.

I hope that i could explain correctly.

Thanks

**Comment by aaronleopold** [comment] 2023-05-31 12:34
Related to / potential duplicate of https://github.com/aaronleopold/stump/issues/40. 

Let me know if I am misunderstanding and this feature request is different 🙂

**Comment by aaronleopold** [comment] 2023-06-01 01:53
Thank you for the clarification, @DieselTech!

@killo3967 if that ticket I linked doesn't quite cover what you're requesting let me know. Otherwise, I'll close this one as a duplicate.

**Comment by aaronleopold** [comment] 2023-06-24 16:46
Closing as duplicate

**Closed by aaronleopold** 2023-06-24 16:46 UTC
Labels: enhancement
