### ISSUE TITLE
[BUG?] very slow in creating library

### ISSUE THREAD

**Issue by Cantello** [stumpapp/stump#427] opened 2024-08-31 16:39 UTC
**Describe the bug**
When adding a library, the media entities are sometimes added quickly but thumbnails take forever or are not generated at all, sometimes, the entities are not created at all.

**To Reproduce**

1. Start the docker container (on debian 12), docker-compose.yml is below
```
  stump:
    image: aaronleopold/stump
    container_name: stump
    volumes:
      - /opt/stump:/config
      - /mnt/_nfs/Stuff:/data_nfs
      - /tmp:/temporary
    ports:
      - 10801:10801
    environment:
      - STUMP_CONFIG_DIR=/config
      - PUID=1000
      - PGID=1000
      - STUMP_VERBOSITY=2
    restart: unless-stopped
```
2. Initialize server
3. Create library (single folder, 40 .cbz files, series-based, thumbnails enabled with 200x350)
4. Library is either created but thumbnails are not generated (or extremely slow, like 1 per minute), OR
5. Library is not created at all ("No books to display", the series is created but with 0 books in it, the files are there in the files tab within the series)

**Expected behavior**
Library is created with thumbnails

**Screenshots**
<details><summary>Click to expand</summary>

<p>

![2024-08-31 18_08_46-Stump _ Test](https://github.com/user-attachments/assets/fd3918a6-4baa-44ea-9816-41bc3a51c5d3)
![2024-08-31 18_09_03-Stump](https://github.com/user-attachments/assets/44a5d726-461d-40f5-996e-45df00ad4b05)
![2024-08-31 18_07_38-Stump _ Home](https://github.com/user-attachments/assets/228b12a1-25e5-489f-bf14-4700792dbea4)

</p>

</details>

**Desktop (please complete the following information):**
Access on Windows, Vivaldi as browser, stump is hosted on docker on debian 12.

**Additional context**
Log file here (maybe not enough and/or too chatty, was using verbosity 3):

https://logpaste.com/6lqmqRvU

The container stats are also interesting, nearly no CPU usage (1-2%) but huge memory usage (2.5GB after 15 minutes and rising).

**Comment by aaronleopold** [comment] 2024-08-31 16:54
Hey 👋 Thanks for the detailed report!

> thumbnails take forever or are not generated at all

Coincidentally, someone else on Discord reported the really slow thumbnail generation. I'm not sure if you're on there, but if you're interested the discussions can be found [here](https://discord.com/channels/972593831172272148/1276284767133896856).

There is already a draft [PR](https://github.com/stumpapp/stump/pull/426) up which I'm hoping will help with this.

> Create library (single folder, 40 .cbz files, series-based, thumbnails enabled with 200x350)

Can you share additional details about your library structure? You said a single folder, so something like?:

```
Root
├── Single Folder of Stuff
│   ├── 40 .cbz files
```

OR 

```
Root
├── 40 .cbz files
```

Or something else? I'm curious if perhaps you are being affected by a recently fixed bug in the scanner (not in latest yet): https://github.com/stumpapp/stump/pull/423

> Library is not created at all ("No books to display", the series is created but with 0 books in it, the files are there in the files tab within the series)

This is an odd scenario. I won't have time to review the logs you provided today, but do you notice the server doing anything when this happens? I'm curious if there is a panic happening somewhere.

> The container stats are also interesting, nearly no CPU usage (1-2%) but huge memory usage (2.5GB after 15 minutes and rising).

If I had to guess, CPU usage is low during a scan but huge during thumbnail generation. A scan doesn't load too much of the files into memory, but to generate thumbnails means we must load a (potentially large) image into memory, convert it to another format, apply transformations (scale, quality, etc). This is another area I'm hopeful the aforementioned PR will help, though.

**Comment by Cantello** [comment] 2024-08-31 18:04
Thanks for the quick reply, I will just experiment around, stump is (not yet) my main comic reader (but will probably be as Komga is probably never going to implement smart filters).

As for your remarks:

> Can you share additional details about your library structure? You said a single folder, so something like?:

The first test library was just 40 books in the root folder, my regular library is roughly as follows, one folder per 
```
.
└── Comics/
    ├── English/
    │   ├── A Gift for a Ghost (2020)
    │   ├── Alan Moore's Neonomicon (2010-2011)
    │   ├── Alan Moore's The Courtyard (2004)
    │   ├── Aliens - Rescue (2019)
    │   └── American Gods/
    │       ├── American Gods - My Ainsel (2018)
    │       ├── American Gods - Shadows (2017)
    │       └── American Gods - The Moment of the Storm (2019-2020)
    └── German/
        ├── Ab Irato (2016)
        ├── Adler ohne Krallen (2012)
        ├── Akira (1991)
        ├── Aldebaran (2010)
        ├── Alice im Wunderland (2010)
        ├── Alice Matheson (2016-2020)
        └── Allein (2008-)
```

> This is an odd scenario. I won't have time to review the logs you provided today, but do you notice the server doing anything when this happens? I'm curious if there is a panic happening somewhere.

Nothing that I am aware of, any idea where I could be looking?

> Edit to add: I assume you are also using a network drive for your books (/mnt/_nfs/Stuff:/data_nfs). This is going to slow things down even more, in general.

I know that this could be a bottleneck (which is why I switched to NFS instead of SMB, the files are served by a Synology NAS) but other comic readers (tried Kavita & Komga) currently do not suffer from any problems.

P.S.: memory usage is now up to 5.8GB, this does somehow not seem quite right... Is this due to the very verbose logging?

**Comment by aaronleopold** [comment] 2024-08-31 18:24
> The first test library was just 40 books in the root folder, my regular library is roughly as follows, one folder per

This sounds like it would trigger that bug I mentioned. The bug is specifically for media files existing in the root of a library. Since it was just a test, it shouldn't otherwise affect you (unless you have files in the library root elsewhere). It should be fixed as of the last `nightly`.

> Nothing that I am aware of, any idea where I could be looking?

Nothing specific, I really am curious what the entire scan would output though. No books is odd, but sporadically is even stranger. In general, keywords to look for in logs include `error`, `warn`, or `panic`.

> P.S.: memory usage is now up to 5.8GB, this does somehow not seem quite right... Is this due to the very verbose logging?

I wouldn't think so, you're mapping to a dir on your host where the logs are written to. I am not sure how long the logs would remain in a buffer somewhere if nobody is attached to it.

Would you be open to spinning up a test container if I were to push an image with the changes from https://github.com/stumpapp/stump/pull/426? I think your setup is a good one for working out some of these issues.

**Comment by Cantello** [comment] 2024-08-31 19:09
> Would you be open to spinning up a test container if I were to push an image with the changes from https://github.com/stumpapp/stump/pull/426? I think your setup is a good one for working out some of these issues.

Absolutely, just tell me what to do. Might take until Monday, though.

One thing that I noticed after starting a new library scan with reduced log verbosity:

```
2024-08-31T18:59:04.918447Z  INFO stump_core::job: Starting job, job_id: 532f68d0-50c8-419f-8b7b-17fdd35e65c0, job_name: "library_scan"
    at core/src/job/mod.rs:619
2024-08-31T18:59:22.479440Z  INFO stump_core::filesystem::scanner::library_scan_job: Executing the init task for library scan
    at core/src/filesystem/scanner/library_scan_job.rs:269
2024-08-31T18:59:22.638665Z  INFO stump_core::filesystem::scanner::library_scan_job: Executing the walk series task for library scan
    at core/src/filesystem/scanner/library_scan_job.rs:407
2024-08-31T19:00:10.251108Z ERROR tower_http::trace::on_failure: response failed, classification: Status code: 500 Internal Server Error, latency: 0 ms
    at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.4.4/src/trace/on_failure.rs:93
```

**Comment by aaronleopold** [comment] 2024-08-31 19:17
> Absolutely, just tell me what to do. Might take until Monday, though.

I appreciate it! No rush on my end. I'll be pushing a `perf-experimental` tag for each commit on that PR. The first job should finish shortly: https://github.com/stumpapp/stump/actions/runs/10647624711/job/29515774379?pr=426

> One thing that I noticed after starting a new library scan with reduced log verbosity (the only real error I found in the log):

Without more verbose logs it's hard to say would could have triggered a 500. I wouldn't necessarily attribute it to the scanner though, likely a red herring. When you start a scan via HTTP call, it sends an internal message to queue the job. The HTTP request should end by the time the job would start. The only time a 500 would happen is if the message to queue the job failed, but since it shows some info level logs from the scanner I don't think that is what is happening.

**Comment by aaronleopold** [comment] 2024-09-03 23:12
See https://github.com/stumpapp/stump/pull/426#issuecomment-2327605352 for some more context

**Comment by Cantello** [comment] 2024-09-04 07:19
I tried the experimental docker image but I guess there is something more afoot here with my setup than just slow thumbnail creation. Somehow, even after two days, the library creation & scanning process was still working and the status just showed `0% complete (0 of 1745 books) 0 in progress`. It also seemed as if the frontend was still working but the backend did not provide any updates, e.g. the settings page was not displayed even though the web page switched to settings. According to `docker ps` the container was still working and logging into the container and installing procps it shows `stump` working as well.

I recreated the container after deleting all user data and it is currently working. 2/125 tasks done after 50 minutes of a library with ~700 books/100GB.

**Comment by aaronleopold** [comment] 2024-09-04 14:04
To be clear, when you say you tried the experimental docker image you mean the literal `experimental` tag or the `perf-experimental` tag I pushed with (potential) improvements?

> It also seemed as if the frontend was still working but the backend did not provide any updates, e.g. the settings page was not displayed even though the web page switched to settings

Yeah that sounds like it was overwhelmed, e.g. no resources available to issue the queries to display misc settings settings so the suspense boundary stays (nothing gets rendered). If you don't have the `Live refetch` preference enabled (settings > appearance) that is _supposed_ to help. I agree, there is clearly something going on here with how your setup is interacting with Stump.

Is there any way for you to profile what is eating the memory, specifically? E.g. if the process is holding any files open, etc.

**Comment by Cantello** [comment] 2024-09-05 08:23
> To be clear, when you say you tried the experimental docker image you mean the literal experimental tag or the perf-experimental tag I pushed with (potential) improvements?

I was using `perf-experimental`.

> Is there any way for you to profile what is eating the memory, specifically? E.g. if the process is holding any files open, etc.

Sorry, I'm not much of a developer (not at all) and thus cannot really help there. If you have any advice on what you'd need, I can go from there. From what I tried:

```
root@3e6fdecd9b67:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   3736  1852 ?        Ss   06:05   0:00 /bin/bash /entrypoint.sh
root          36  0.0  0.0   6144  1408 ?        S    06:05   0:00 su stump -c /app/stump
stump         37  1.0  5.3 3232524 871560 ?      Ssl  06:05   1:09 /app/stump
root         107  0.0  0.0   3976  2952 pts/0    Ss   06:08   0:00 /bin/bash
root         715  0.0  0.0   7640  2584 pts/0    R+   07:57   0:00 ps aux
```

```
root@3e6fdecd9b67:/# lsof -p 37
COMMAND PID  USER   FD      TYPE DEVICE SIZE/OFF NODE NAME
stump    37 stump  cwd   unknown                      /proc/37/cwd (readlink: Permission denied)
stump    37 stump  rtd   unknown                      /proc/37/root (readlink: Permission denied)
stump    37 stump  txt   unknown                      /proc/37/exe (readlink: Permission denied)
stump    37 stump    0   unknown                      /proc/37/fd/0 (readlink: Permission denied)
stump    37 stump    1   unknown                      /proc/37/fd/1 (readlink: Permission denied)
stump    37 stump    2   unknown                      /proc/37/fd/2 (readlink: Permission denied)
[... lots more lines, 45 file descriptors in total]
```

```
root@3e6fdecd9b67:/# free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       6.4Gi       3.4Gi        80Mi       5.7Gi       8.4Gi
Swap:            0B          0B          0B
```

**Comment by aaronleopold** [comment] 2024-09-05 19:30
> Sorry, I'm not much of a developer (not at all) and thus cannot really help there

No worries! I appreciate what you provided. Unfortunately nothing really sticks out to me, aside from curiosity around those `Permission denied`s. However, I was able to finally reproduce your issues! It's my fault, I should have really tried my initial investigations in a docker container, as that is the key part but everything I tried was local for convenience. 

I was able to get a quickly growing memory usage for pretty much any scenario (host mount, SMB, NFS), getting to 10GB easily within 20 minutes. When cancelling the scan, the memory stabilizes and the OS does not free it. I just killed the container after 30 minutes sitting around 10GB idle. I'm not 100% what the next steps should be TBH, since I only am able to experience this in docker I'm thinking:

- Experiment with allocators (e.g. https://crates.io/crates/jemallocator) when running in docker
- Experiment with different base image(s)
- Remove all IO operations and slowly add them back (this is sort of extremely tedious since I have to rebuild an image each time, should be last resort)

**Comment by aaronleopold** [comment] 2024-09-05 23:15
Okay so I might have found something!

I think the root cause of this is an issue in the `zip` crate. I initially became suspicious of this when:

1. Using a different allocator (tried mimalloc and jemalloc) didn't help or really change anything
2. Changing to distroless image didn't help
3. Scanning a (granted, much smaller) ebook library didn't trigger the issue
4. Refreshing the `books` page for a library filled with ZIP files just kept increasing memory usage
5. Refreshing the `books` page for a library filled with ebooks didn't increase memory usage :eyes:

It's important to note that the `epub-rs` library uses a different, older version of the `zip` crate. This crate was updated in this project a couple months ago (https://github.com/stumpapp/stump/pull/353). So to verify that there is something funky going on with the `zip` crate, I downgraded and testsed twice:

1. Downgraded the `zip` crate to `0.6.6`
2. Downgrade the `zip` crate to `1.1.3` (the version used in `epub-rs`)

The results were pretty much the same between the versions. The memory usage definitely did still increase during the duration of the scan, but we're talking magnitudes less than before. I was getting to over 10GB of usage within 20 minutes of scanning the NFS mount, but with the downgraded `zip` crate, I was at 256.2MiB after 8 minutes at which point the scan was complete. Memory dropped back down by about 10MiB, so it's still holding on to memory. In case the numbers aren't clear either wrt the timing, the NFS mount took 8 minutes to scan 1546 books after downgrading. If you recall/read any of the comments in the linked PR, this is a substantial difference to say the least lol

I think next steps will be to push another `perf-experimental` image with the downgraded `zip` crate and see if the issue is improved at all on your end. I might eagerly downgrade for the `0.0.6` release I was planning on doing this weekend, as well. As a side note, I'm contemplating keeping the distroless base image since it shrunk the image by 67% in size, IDK if anyone has thoughts on that.

I'll also try to find time to create a good reproduction to hand off to the `zip` crate maintainers to hopefully figure out what might be happening.

**Comment by aaronleopold** [comment] 2024-09-06 23:42
@Cantello I'm going to plan on merging the linked PR sometime over the weekend. If you're able to, let me know whether the latest `perf-experimental` improves the situation on your end at all

**Comment by aaronleopold** [comment] 2024-09-09 14:46
Awesome, thanks for re-testing with the updates! I'll go ahead and close out this issue now that the slowness aspect has been resolved. I'll try and keep an eye on the memory usage in docker, it's odd that running Stump outside docker doesn't have the same issue. If you find the memory worsens, feel free to create a separate issue.

Thanks for outlining your experience and pointing the slowness out! You directly helped in figuring out the huge performance regression 🤝

**Closed by aaronleopold** 2024-09-09 14:46 UTC
Labels: bug
