### ISSUE TITLE
[BUG] Arrow keys stop working after a few seconds

### ISSUE THREAD

**Issue by jayjoshi64** [stumpapp/stump#357] opened 2024-06-26 17:44 UTC
**Describe the bug**
Right/Left arrow key should turn the page, but after a few seconds it stops working. It no longer turns the page no matter how many times I press it.  After I click the page, it again works for a few seconds.  in my opinion, this is a core functionality that should work flawlessly.

**To Reproduce**
1. In the web, open any book. 
2. Keep hitting the right arrow to turn the page 
3. in 4-5 seconds, it'll stop working. Sometimes it takes 8-9 seconds as well.

**Expected behavior**
The page should keep turning with just right/left arrows. I should not be needed to use mouse click

**Screenshots**
I don't think this would help. 

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Edge, Chrome

**Comment by aaronleopold** [comment] 2024-06-26 19:23
I just reproduced on my own instance. It seems to be connected to a chapter load, e.g. the arrow keys work consistently until the chapter changes. Once the chapter changes, I have to click back into the iframe in order for the events to be picked up. This is *particularly* irritating in the beginning of a book, since a 'chapter' could be 1-2 pages 😅 

I'll definitely try to look into this over the weekend since I agree that arrow navigation is pretty important for any reader, however I am a bit pessimistic in finding a good solution. This is mostly because working with EPUB.js, which the reader is built with, has been a large pain point. While the mobile app, in general, is much less of a priority, I have loose plans to use Readium there. A migration away from EPUB.js to Readium on the webapp, as well, might be in the future at some point for uniformity. A bit of a ramble, but I'll update this ticket if I come up with a fix 👍

**Comment by aaronleopold** [comment] 2024-06-29 20:05
Should be resolved by #359

**Closed by aaronleopold** 2024-06-29 20:05 UTC
Labels: bug
